version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1663251395
layout:
  top: {  }
  /navigation/:
    -
      - jlnavbar-1212
  /slideshow/:
    -
      - position-position-1327
  hero: {  }
  header: {  }
  above: {  }
  feature: {  }
  showcase: {  }
  utility: {  }
  /container-main/:
    -
      -
        'sidebar 10':
          -
            - spacer-3076
      -
        'mainbar 80':
          -
            - system-content-7930
          -
            - position-position-4700
      -
        'aside 10':
          -
            - spacer-6477
  expanded: {  }
  extension: {  }
  bottom: {  }
  below: {  }
  footer: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    attributes:
      boxed: '2'
      maxwidth: '4'
      class: ''
      variations: 'nomarginall nopaddingall'
  slideshow:
    type: section
    attributes:
      boxed: '2'
      maxwidth: ''
      class: ''
      variations: 'nomarginall nopaddingall'
  hero:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  header:
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  feature:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  showcase:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
      variations: 'nomarginall nopaddingall'
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: 'nomarginall nopaddingall'
    block:
      variations: 'nomarginall nopaddingall'
  aside:
    attributes:
      class: ''
      variations: 'nomarginall nopaddingall'
  container-main:
    attributes:
      boxed: '2'
      maxwidth: '2'
      class: jl-section
      extra: {  }
  expanded:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  extension:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  bottom:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  below:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  copyright:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  jlnavbar-1212:
    attributes:
      text: 'Colegio San Ignacio'
      image: 'gantry-media://colegio/LOGO OFICIAL CSI 1.png'
      svg_support: '0'
      height: 130px
      mobile_logo_image: 'gantry-media://colegio/LOGO OFICIAL CSI 1.png'
      image_height: 50px
      menu: colegio-san-ignacio
      base: /
      startLevel: '1'
      maxLevels: '0'
      renderTitles: '0'
      hoverExpand: '1'
      parrentIcon: '1'
      forceTarget: '0'
      menu_visibility: l
      m_sticky: ''
      ms_top: '1'
      ms_offset: '1'
      mobile_logo: center
      mobile_menu_toggle: right
      toggle_color: '#000000'
      toggle_color_hover: '#00539b'
      toggle_text_fontsize: ''
      menu_animation: offcanvas
      close_button: '1'
      offcanvas_inverse: dark
      overlay: '1'
      animation_mode: slide
      flip_offcanvas: '1'
      nav_style: ''
      nav_divider: '0'
      nav_center: '0'
      modal_vertically: '0'
      module_id: ''
      navbar_style: extended
      transparent_header: ''
      mobile_text_color: '#e0e0e0'
      navbar_color: '#000000'
      navbar_fontsize: 15px
      navbar_text_transform: ''
      navbar_hover_color: '#00539b'
      navbar_active_color: '#00539b'
      dropdown_bg: '#e0e0e0'
      dropdown_border_radius: 5px
      dropdown_color: '#000000'
      dropdown_padding: 10px
      dropdown_alignment: center
      navbar_dropdown_animation: slide-left
      dropdown_stretch: '0'
      dropdown_navbar_hover_color: '#00539b'
      layout: right
      sticky: sticky
      container_maxwidth: custom
      ct_container_width: 100rem
      navbar_height: 100px
      main_nav_margin: '1'
    block:
      variations: 'nomarginall nopaddingall'
  position-position-1327:
    title: 'Module Position'
    attributes:
      key: sliderarticulos
      chrome: none
  position-position-4700:
    title: 'Module Position'
    attributes:
      key: articulos
      chrome: none
