name: 15
timestamp: 1663247726
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1663247725
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-3001: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-1881: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-1562: Copyright
  social:
    social-7082: Social
  branding:
    branding-3786: Branding
  mobile-menu:
    mobile-menu-4808: 'Mobile Menu'
inherit: {  }
