version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1663251395
layout:
  top: {  }
  navigation: {  }
  /slideshow/:
    -
      - position-position-7776
  hero: {  }
  header: {  }
  above: {  }
  feature: {  }
  showcase: {  }
  utility: {  }
  /container-main/:
    -
      -
        'sidebar 5':
          -
            - spacer-5618
      -
        'mainbar 60':
          -
            - jltext-2198
          -
            - system-content-4823
          -
            - position-position-6582
      -
        'aside 35':
          -
            - position-position-4605
          -
            - custom-7318
  /expanded/:
    -
      - 'jlvideo-3477 65'
      - 'jlimage-2793 35'
  /extension/: {  }
  bottom: {  }
  below: {  }
  footer: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  navigation:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  slideshow:
    type: section
    attributes:
      boxed: '2'
      maxwidth: ''
      class: ''
      variations: 'nomarginall nopaddingall'
  hero:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  header:
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  above:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  feature:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  showcase:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  utility:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
      variations: 'nomarginall nopaddingall'
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: jl-section-xsmall
    block:
      variations: 'nomarginall nopaddingall'
  aside:
    attributes:
      class: ''
      variations: jl-section
  container-main:
    attributes:
      boxed: '2'
      maxwidth: '2'
      class: jl-section
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: '2'
      maxwidth: '2'
      class: ''
      variations: ''
  extension:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  bottom:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  below:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  copyright:
    type: section
    inherit:
      outline: '17'
      include:
        - attributes
        - block
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  position-position-7776:
    title: 'Posición del módulo'
    attributes:
      key: sliderarticulos
      chrome: none
    block:
      variations: 'nomarginall nopaddingall'
  spacer-5618:
    title: Espaciador
  jltext-2198:
    title: 'Texto JL'
    attributes:
      content: ''
      dropcap: '0'
      text_columns: none
      column_divider: '0'
      column_breakpoint: m
      twig: '0'
      filter: '0'
      text_color: emphasis
      customize_content_color: '#00539b'
      customize_content_fontsize: '35'
      text_style: lead
      text_size: large
      class: ''
      particle_title: 'Últimas Noticias'
      particle_title_style: h3
      particle_title_decoration: none
      particle_title_align: left
      particle_predefined_color: emphasis
      particle_title_color: '#5a5c5e'
      particle_title_fontsize: '40'
      particle_title_text_transform: ''
      particle_title_font_weight: bold
      particle_title_element: h1
      align: inherit
      breakpoint: always
      fallback: inherit
      g_maxwidth: inherit
      g_maxwidth_alignment: left
      g_maxwidth_breakpoint: always
      margin: inherit
      visibility: inherit
      animation: inherit
      animation_delay: ''
      animation_repeat: disabled
      pa_horizontal_start: ''
      pa_horizontal_end: ''
      pa_vertical_start: ''
      pa_vertical_end: ''
      scale_start: ''
      scale_end: ''
      rotate_start: ''
      rotate_end: ''
      opacity_start: ''
      opacity_end: ''
      easing: ''
      pa_viewport: ''
      pa_z_index: '0'
      pa_breakpoint: always
      parallax_image: ''
      background_image_size: auto
      background_image_position: center-center
      bg_image_effect: ''
      horizontal_start: '0'
      horizontal_end: '0'
      vertical_start: '0'
      vertical_end: '0'
      parallax_easing: ''
      parallax_bg_breakpoint: always
      parallax_bg_visibility: always
      parallax_bg_color: ''
      blendmode: inherit
      parallax_bg_overlay: ''
      container_maxwidth: default
      bg_container_width: ''
      viewport_height: none
      padding: default
      vertical_alignment: none
      parallax_text_color: default
  system-content-4823:
    title: 'Contenido de página'
  position-position-6582:
    title: 'Posición del módulo'
    attributes:
      key: articulo
      chrome: none
  position-position-4605:
    title: 'Posición del módulo'
    attributes:
      key: carrete-noticias
      chrome: none
  custom-7318:
    title: maps
    attributes:
      html: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3923.0296509872182!2d-66.856754!3d10.498328700000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c2a590738da8287%3A0x695a635f72aa10be!2sColegio%20San%20Ignacio%20de%20Loyola!5e0!3m2!1ses!2sve!4v1663159736801!5m2!1ses!2sve" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>'
  jlvideo-3477:
    title: 'Vídeo JL'
    attributes:
      source: youtube
      video: 'https://www.youtube.com/watch?v=-5X6EWJXzv8'
      local_video: ''
      posterimage: ''
      video_frame_width: '850'
      video_frame_height: '500'
      controls: enabled
      loop: enabled
      muted: enabled
      play_inline: enabled
      lazy_video: enabled
      autoplay: 'on'
      video_box_shadow: xlarge
      class: ''
      link_frame: '0'
      link_button: '0'
      image_transition: none
      overlay_style: jl-overlay-default
      overlay_padding: default
      overlay_position: center
      overlay_margin: none
      image_width: ''
      image_height: ''
      border: none
      box_shadow: none
      box_shadow_hover: none
      popup_type: modal
      close: outside
      centermodal: '1'
      particle_title: ''
      particle_title_style: h3
      particle_title_decoration: none
      particle_title_align: inherit
      particle_predefined_color: default
      particle_title_color: ''
      particle_title_fontsize: ''
      particle_title_text_transform: ''
      particle_title_font_weight: ''
      particle_title_element: h3
      align: inherit
      breakpoint: always
      fallback: inherit
      g_maxwidth: inherit
      g_maxwidth_alignment: left
      g_maxwidth_breakpoint: always
      margin: inherit
      visibility: inherit
      animation: inherit
      animation_delay: ''
      animation_repeat: disabled
      pa_horizontal_start: ''
      pa_horizontal_end: ''
      pa_vertical_start: ''
      pa_vertical_end: ''
      scale_start: ''
      scale_end: ''
      rotate_start: ''
      rotate_end: ''
      opacity_start: ''
      opacity_end: ''
      easing: ''
      pa_viewport: ''
      pa_z_index: '0'
      pa_breakpoint: always
      parallax_image: ''
      background_image_size: auto
      background_image_position: center-center
      bg_image_effect: ''
      horizontal_start: '0'
      horizontal_end: '0'
      vertical_start: '0'
      vertical_end: '0'
      parallax_easing: ''
      parallax_bg_breakpoint: always
      parallax_bg_visibility: always
      parallax_bg_color: ''
      blendmode: inherit
      parallax_bg_overlay: ''
      container_maxwidth: default
      bg_container_width: ''
      viewport_height: none
      padding: default
      vertical_alignment: none
      parallax_text_color: default
    block:
      variations: center
  jlimage-2793:
    title: 'Imagen JL'
    attributes:
      image: 'gantry-media://colegio/iphoneinsta-removebg-preview 1.png'
      image_alt: ''
      link: 'https://www.instagram.com/sanignaciocaracas/?hl=es'
      target: _blank
      border: rounded
      box_shadow: medium
      box_shadow_hover: large
      extra_shadow: '0'
      image_transition: scale-up
      image_width: ''
      image_height: ''
      class: ''
      md_title: ''
      md_content: ''
      twig: '0'
      filter: '0'
      title_style: default
      title_decoration: none
      title_color: default
      title_element: h3
      close_button: outside
      center_modal: '0'
      content_style: default
      content_margin_top: default
      particle_title: ''
      particle_title_style: h3
      particle_title_decoration: none
      particle_title_align: inherit
      particle_predefined_color: default
      particle_title_color: ''
      particle_title_fontsize: ''
      particle_title_text_transform: ''
      particle_title_font_weight: ''
      particle_title_element: h3
      align: inherit
      breakpoint: always
      fallback: inherit
      g_maxwidth: inherit
      g_maxwidth_alignment: left
      g_maxwidth_breakpoint: always
      margin: inherit
      visibility: inherit
      animation: scale-up
      animation_delay: '500'
      animation_repeat: enabled
      pa_horizontal_start: ''
      pa_horizontal_end: ''
      pa_vertical_start: ''
      pa_vertical_end: ''
      scale_start: ''
      scale_end: ''
      rotate_start: ''
      rotate_end: ''
      opacity_start: ''
      opacity_end: ''
      easing: ''
      pa_viewport: ''
      pa_z_index: '0'
      pa_breakpoint: always
      parallax_image: ''
      background_image_size: auto
      background_image_position: center-center
      bg_image_effect: ''
      horizontal_start: '0'
      horizontal_end: '0'
      vertical_start: '0'
      vertical_end: '0'
      parallax_easing: ''
      parallax_bg_breakpoint: always
      parallax_bg_visibility: always
      parallax_bg_color: ''
      blendmode: inherit
      parallax_bg_overlay: ''
      container_maxwidth: default
      bg_container_width: ''
      viewport_height: none
      padding: default
      vertical_alignment: none
      parallax_text_color: default
    block:
      variations: center
