name: 22
timestamp: 1664388334
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1663251395
positions:
  correos-institucionales: 'Module Position'
  enlaces-interes: 'Module Position'
  formulario-contacto: 'Module Position'
  top-a: 'Top A'
  sliderarticulos: 'Module Position'
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  hero: Hero
  above: Above
  feature: Feature
  showcase: Showcase
  utility: Utility
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  below: Below
  copyright: Copyright
  header: Header
  sidebar: Sidebar
  aside: Aside
  mainbar: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  spacer:
    spacer-7087: Spacer
    spacer-6988: Spacer
    spacer-3473: Spacer
    spacer-4934: Spacer
    spacer-7379: Spacer
    spacer-5711: Spacer
  custom:
    custom-2565: 'Custom HTML'
    custom-6334: 'Custom HTML'
    custom-1789: 'HTML personalizado'
    custom-3392: 'HTML personalizado'
  position:
    position-position-2154: 'Module Position'
    position-position-5899: 'Module Position'
    position-position-8439: 'Module Position'
    position-position-8103: 'Top A'
    position-position-8679: 'Module Position'
  jldivider:
    jldivider-8064: 'JL Divider'
  content:
    system-content-6507: 'Page Content'
  jlnavbar:
    jlnavbar-1212: 'Barra de navegación JL'
  jlimage:
    jlimage-9266: 'Imagen JL'
  copyright:
    copyright-4104: 'Derechos de autor'
inherit:
  17:
    top: top
    navigation: navigation
    hero: hero
    header: header
    above: above
    feature: feature
    showcase: showcase
    utility: utility
    expanded: expanded
    extension: extension
    bottom: bottom
    below: below
    footer: footer
    copyright: copyright
    position-position-8103: position-position-2946
    jlnavbar-1212: jlnavbar-7196
    spacer-7379: spacer-6153
    custom-1789: custom-2811
    jlimage-9266: jlimage-1952
    custom-3392: custom-5889
    spacer-5711: spacer-2830
    copyright-4104: copyright-9780
  21:
    slideshow: slideshow
    spacer-7087: spacer-3076
    system-content-6507: system-content-7930
    spacer-4934: spacer-6477
    position-position-8679: position-position-1327
  default:
    offcanvas: offcanvas
