version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1663247725
layout:
  /header/:
    -
      - 'logo-3383 30'
      - 'spacer-9478 70'
  /main/:
    -
      - system-messages-6809
    -
      - system-content-3944
  /footer/:
    -
      - position-footer
    -
      - 'copyright-8256 40'
      - 'spacer-7090 30'
      - 'branding-3784 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
