preset: preset1
navigation:
  background: '#f7f7f7'
footer:
  background: '#00539b'
  text-color: 'rgba(255, 255, 255, 0.86)'
  link-hover-color: '#00539b'
copyright:
  link-color: '#00539b'
  link-hover-color: '#00539b'
offcanvas:
  text-color-active: '#00539b'
