version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1663251395
layout:
  /top/:
    -
      - position-position-8328
  /navigation/:
    -
      - jlnavbar-2718
  /hero/:
    -
      - position-position-5320
  /slideshow/:
    -
      - position-position-7292
  /header/:
    -
      - position-position-3605
  /above/:
    -
      - position-position-2010
  /feature/:
    -
      - position-position-7784
  /showcase/:
    -
      - position-position-8752
  /utility/:
    -
      - position-position-4593
  /container-main/:
    -
      -
        'sidebar 25':
          -
            - position-position-2532
      -
        'mainbar 50':
          -
            - system-messages-8907
          -
            - position-position-6716
          -
            - system-content-2965
      -
        'aside 25':
          -
            - position-position-1432
  /expanded/:
    -
      - position-position-4069
  /extension/:
    -
      - position-position-4868
  /bottom/:
    -
      - position-position-4901
  /below/:
    -
      - position-position-6202
  /footer/:
    -
      - position-position-8699
  /copyright/:
    -
      - copyright-6042
  offcanvas: {  }
structure:
  top:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: border-bottom
      variations: 'nopaddingbottom nopaddingtop'
  navigation:
    type: section
    attributes:
      boxed: '2'
      maxwidth: ''
      class: ''
      variations: 'nomarginall nopaddingall'
  hero:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section-xlarge
  slideshow:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  header:
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  above:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  feature:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  utility:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: ''
  aside:
    attributes:
      class: ''
      variations: ''
  container-main:
    attributes:
      boxed: ''
      maxwidth: ''
      class: jl-section
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  extension:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  bottom:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  below:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  footer:
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  copyright:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: 'nomargintop nomarginbottom'
  offcanvas:
    attributes:
      swipe: '0'
content:
  position-position-8328:
    title: 'Top A'
    attributes:
      key: top-a
  jlnavbar-2718:
    title: 'JL Navbar'
    attributes:
      text: Meta
      hoverExpand: '1'
      menu_visibility: m
      m_sticky: stickyonscroll
      mobile_logo: center
      mobile_menu_toggle: left
      menu_animation: offcanvas
      close_button: '1'
      module_id: ''
      navbar_style: extended
      transparent_header: light
      logo_color: '#ffffff'
      layout: right
      sticky: stickyonscroll
      search_pos: navbar
      search_style: modal
      container_maxwidth: default
      main_nav_margin: '1'
    block:
      class: square-icon
  position-position-5320:
    title: Hero
    attributes:
      key: breadcrumbs
    block:
      variations: jl-light
  position-position-7292:
    title: Slideshow
    attributes:
      key: slideshow
  position-position-3605:
    title: 'Header A'
    attributes:
      key: header-a
  position-position-2010:
    title: 'Above A'
    attributes:
      key: above-a
  position-position-7784:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-8752:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-position-4593:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-2532:
    title: 'Sidebar A'
    attributes:
      key: sidebar-a
  position-position-6716:
    title: 'Mainbar A'
    attributes:
      key: mainbar-a
  position-position-1432:
    title: 'Aside A'
    attributes:
      key: aside-a
  position-position-4069:
    title: 'Expanded A'
    attributes:
      key: expanded-a
  position-position-4868:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-4901:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-position-6202:
    title: 'Below A'
    attributes:
      key: below-a
  position-position-8699:
    title: 'Footer A'
    attributes:
      key: footer-a
  copyright-6042:
    attributes:
      owner: 'Meta Joomla 4 template by <a href="https://joomlead.com/" target="_blank">Joomlead</a>'
    block:
      variations: center
