version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1663251395
layout:
  /top/:
    -
      - position-position-2946
  /navigation/:
    -
      - jlnavbar-7196
  /slideshow/:
    -
      - position-position-8676
  /hero/: {  }
  /header/: {  }
  /above/: {  }
  /feature/: {  }
  /showcase/: {  }
  /utility/: {  }
  /container-main/:
    -
      -
        'sidebar 5': {  }
      -
        'mainbar 90':
          -
            - 'position-position-5723 25'
            - 'position-position-2929 25'
            - 'position-position-1887 25'
            - 'position-position-1073 25'
          -
            - jldivider-8968
          -
            - jlanimatedtext-4124
          -
            - jldivider-4245
          -
            - 'position-position-3182 25'
            - 'position-position-5877 25'
            - 'position-position-1101 25'
            - 'position-position-8932 25'
      -
        'aside 5': {  }
  /expanded/: {  }
  /extension/: {  }
  /bottom/: {  }
  /below/: {  }
  /footer/:
    -
      - 'spacer-6153 5'
      - 'custom-2811 32'
      - 'jlimage-1952 26'
      - 'custom-5889 32'
      - 'spacer-2830 5'
  /copyright/:
    -
      - copyright-9780
  offcanvas: {  }
structure:
  top:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: border-bottom
      variations: 'nopaddingbottom nopaddingtop'
  navigation:
    type: section
    attributes:
      boxed: '2'
      maxwidth: '4'
      class: ''
      variations: 'nomarginall nopaddingall'
  slideshow:
    type: section
    attributes:
      boxed: '2'
      maxwidth: ''
      class: ''
      variations: 'nomarginall nopaddingall'
  hero:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  header:
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  above:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  feature:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  utility:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
      variations: 'nomarginall nopaddingall'
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
      variations: 'nomarginall nopaddingall'
    block:
      variations: 'nomarginall nopaddingall'
  aside:
    attributes:
      class: ''
      variations: 'nomarginall nopaddingall'
  container-main:
    attributes:
      boxed: '2'
      maxwidth: '2'
      class: jl-section
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section-large
  extension:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  bottom:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  below:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: jl-section
  footer:
    attributes:
      boxed: '2'
      maxwidth: '2'
      class: ''
      variations: nomarginall
  copyright:
    type: section
    attributes:
      boxed: ''
      maxwidth: ''
      class: ''
      variations: 'nomargintop nomarginbottom'
  offcanvas:
    attributes:
      position: g-offcanvas-left
      class: ''
      extra: {  }
      swipe: '0'
      css3animation: '1'
content:
  position-position-2946:
    title: 'Top A'
    attributes:
      enabled: 0
      key: top-a
  jlnavbar-7196:
    title: 'Barra de navegación JL'
    attributes:
      text: Meta
      image: 'gantry-media://colegio/LOGO OFICIAL CSI 1.png'
      height: 130px
      mobile_logo_image: 'gantry-media://colegio/LOGO OFICIAL CSI 1.png'
      image_height: 50px
      menu: menu-inicial
      menu_visibility: l
      m_sticky: ''
      ms_top: '1'
      ms_offset: '1'
      mobile_logo: center
      mobile_menu_toggle: right
      toggle_color: '#000000'
      toggle_color_hover: '#000000'
      toggle_text_fontsize: '15'
      menu_animation: offcanvas
      close_button: '1'
      offcanvas_inverse: dark
      overlay: '1'
      animation_mode: slide
      flip_offcanvas: '1'
      nav_style: ''
      nav_divider: '1'
      nav_center: '0'
      modal_vertically: '0'
      nav_color_header: ''
      module_id: ''
      navbar_style: extended
      mobile_text_color: '#e0e0e0'
      navbar_color: '#000000'
      navbar_fontsize: 15px
      navbar_hover_color: '#00539b'
      navbar_active_color: '#00539b'
      dropdown_bg: '#e0e0e0'
      dropdown_border_radius: 5px
      dropdown_color: '#000000'
      dropdown_padding: 10px
      dropdown_alignment: center
      navbar_dropdown_animation: slide-left
      dropdown_navbar_hover_color: '#00539b'
      layout: right
      sticky: sticky
      container_maxwidth: custom
      ct_container_width: 100rem
      navbar_height: 100px
    block:
      class: square-icon
      variations: 'nomarginall nopaddingall'
  position-position-8676:
    title: 'Module Position'
    attributes:
      key: sliderprincipal
      chrome: none
    block:
      variations: 'nomarginall nopaddingall'
  position-position-5723:
    title: 'Module Position'
    attributes:
      key: organizacion1-1
      chrome: none
    block:
      variations: center
  position-position-2929:
    title: 'Module Position'
    attributes:
      key: organizacion2
      chrome: none
    block:
      variations: center
  position-position-1887:
    title: 'Module Position'
    attributes:
      key: organizacion3
      chrome: none
    block:
      variations: center
  position-position-1073:
    title: 'Module Position'
    attributes:
      key: organizacion4
      chrome: none
    block:
      variations: center
  jldivider-8968:
    title: 'Divisor JL'
    attributes:
      divider_style: default
      divider_element: hr
      divider_align: center
      divider_breakpoint: always
      divider_fallback: inherit
      divider_border: '1'
      divider_color: ''
      class: ''
      particle_title: ''
      particle_title_style: h3
      particle_title_decoration: none
      particle_title_align: inherit
      particle_predefined_color: default
      particle_title_color: ''
      particle_title_fontsize: ''
      particle_title_text_transform: ''
      particle_title_font_weight: ''
      particle_title_element: h3
      align: inherit
      breakpoint: always
      fallback: inherit
      g_maxwidth: inherit
      g_maxwidth_alignment: left
      g_maxwidth_breakpoint: always
      margin: inherit
      visibility: inherit
      animation: inherit
      animation_delay: ''
      animation_repeat: disabled
      pa_horizontal_start: ''
      pa_horizontal_end: ''
      pa_vertical_start: ''
      pa_vertical_end: ''
      scale_start: ''
      scale_end: ''
      rotate_start: ''
      rotate_end: ''
      opacity_start: ''
      opacity_end: ''
      easing: ''
      pa_viewport: ''
      pa_z_index: '0'
      pa_breakpoint: always
  jlanimatedtext-4124:
    title: 'Texto animado JL'
    attributes:
      intro_text: 'Celebra con Nosotros los 100 años del colegio San Igancio'
      animated: {  }
      after_text: ''
      headlines: zoom
      class: ''
      style: h1
      title_text_color: primary
      title_color: ''
      title_fontsize: '35'
      title_text_transform: ''
      title_font_weight: bold
      titletag: h3
      subtitle_style: default
      subtitle_fontsize: ''
      sub_text_color: default
      subtitle_color: ''
      particle_title: ''
      particle_title_style: h3
      particle_title_decoration: none
      particle_title_align: inherit
      particle_predefined_color: default
      particle_title_color: ''
      particle_title_fontsize: ''
      particle_title_text_transform: ''
      particle_title_font_weight: ''
      particle_title_element: h3
      align: inherit
      breakpoint: always
      fallback: inherit
      g_maxwidth: inherit
      g_maxwidth_alignment: left
      g_maxwidth_breakpoint: always
      margin: inherit
      visibility: inherit
      animation: scale-up
      animation_delay: '500'
      animation_repeat: enabled
      pa_horizontal_start: ''
      pa_horizontal_end: ''
      pa_vertical_start: ''
      pa_vertical_end: ''
      scale_start: ''
      scale_end: ''
      rotate_start: ''
      rotate_end: ''
      opacity_start: ''
      opacity_end: ''
      easing: ''
      pa_viewport: ''
      pa_z_index: '0'
      pa_breakpoint: always
      parallax_image: 'gantry-media://colegio/fondo.jpg'
      background_image_size: cover
      background_image_position: center-center
      bg_image_effect: ''
      horizontal_start: '0'
      horizontal_end: '0'
      vertical_start: '0'
      vertical_end: '0'
      parallax_easing: ''
      parallax_bg_breakpoint: always
      parallax_bg_visibility: always
      parallax_bg_color: ''
      blendmode: inherit
      parallax_bg_overlay: ''
      container_maxwidth: default
      bg_container_width: ''
      viewport_height: expand
      padding: xlarge
      vertical_alignment: bottom
      parallax_text_color: default
    block:
      variations: 'nopaddingall nomarginall'
  jldivider-4245:
    title: 'Divisor JL'
    attributes:
      divider_style: default
      divider_element: hr
      divider_align: center
      divider_breakpoint: always
      divider_fallback: inherit
      divider_border: '1'
      divider_color: ''
      class: ''
      particle_title: ''
      particle_title_style: h3
      particle_title_decoration: none
      particle_title_align: inherit
      particle_predefined_color: default
      particle_title_color: ''
      particle_title_fontsize: ''
      particle_title_text_transform: ''
      particle_title_font_weight: ''
      particle_title_element: h3
      align: inherit
      breakpoint: always
      fallback: inherit
      g_maxwidth: inherit
      g_maxwidth_alignment: left
      g_maxwidth_breakpoint: always
      margin: inherit
      visibility: inherit
      animation: inherit
      animation_delay: ''
      animation_repeat: disabled
      pa_horizontal_start: ''
      pa_horizontal_end: ''
      pa_vertical_start: ''
      pa_vertical_end: ''
      scale_start: ''
      scale_end: ''
      rotate_start: ''
      rotate_end: ''
      opacity_start: ''
      opacity_end: ''
      easing: ''
      pa_viewport: ''
      pa_z_index: '0'
      pa_breakpoint: always
  position-position-3182:
    title: 'Posición del módulo'
    attributes:
      key: Directivo1
      chrome: none
    block:
      variations: center
  position-position-5877:
    title: 'Posición del módulo'
    attributes:
      key: Directivo2
      chrome: none
    block:
      variations: center
  position-position-1101:
    title: 'Posición del módulo'
    attributes:
      key: Directivo3
      chrome: none
    block:
      variations: center
  position-position-8932:
    title: 'Posición del módulo'
    attributes:
      key: Directivo4
      chrome: none
    block:
      variations: center
  custom-2811:
    title: 'HTML personalizado'
    attributes:
      html: '<p>El Colegio San Ignacio es una institución educativa perteneciente a la Compañía de Jesús, es así como la Comunidad Educativa del Colegio San Ignacio, a partir de los retos que se le presentan a la Sociedad Venezolana y de las propuestas de la Compañía de Jesús para la Provincia de Venezuela, asume como su Misión y su Visión.</p>'
    block:
      variations: nomarginall
      extra:
        -
          style: 'text-align: justify'
  jlimage-1952:
    title: 'Imagen JL'
    attributes:
      image: 'gantry-media://colegio/LOGO OFICIAL CSI 1.png'
      image_alt: ''
      link: ''
      target: _self
      border: none
      box_shadow: none
      box_shadow_hover: none
      extra_shadow: '0'
      image_transition: ''
      image_width: '150'
      image_height: '150'
      class: ''
      md_title: ''
      md_content: ''
      twig: '0'
      filter: '0'
      title_style: default
      title_decoration: none
      title_color: default
      title_element: h3
      close_button: outside
      center_modal: '0'
      content_style: default
      content_margin_top: default
      particle_title: ''
      particle_title_style: h3
      particle_title_decoration: none
      particle_title_align: inherit
      particle_predefined_color: default
      particle_title_color: ''
      particle_title_fontsize: ''
      particle_title_text_transform: ''
      particle_title_font_weight: ''
      particle_title_element: h3
      align: inherit
      breakpoint: always
      fallback: inherit
      g_maxwidth: inherit
      g_maxwidth_alignment: left
      g_maxwidth_breakpoint: always
      margin: inherit
      visibility: inherit
      animation: inherit
      animation_delay: ''
      animation_repeat: disabled
      pa_horizontal_start: ''
      pa_horizontal_end: ''
      pa_vertical_start: ''
      pa_vertical_end: ''
      scale_start: ''
      scale_end: ''
      rotate_start: ''
      rotate_end: ''
      opacity_start: ''
      opacity_end: ''
      easing: ''
      pa_viewport: ''
      pa_z_index: '0'
      pa_breakpoint: always
      parallax_image: ''
      background_image_size: auto
      background_image_position: center-center
      bg_image_effect: ''
      horizontal_start: '0'
      horizontal_end: '0'
      vertical_start: '0'
      vertical_end: '0'
      parallax_easing: ''
      parallax_bg_breakpoint: always
      parallax_bg_visibility: always
      parallax_bg_color: ''
      blendmode: inherit
      parallax_bg_overlay: ''
      container_maxwidth: default
      bg_container_width: ''
      viewport_height: none
      padding: default
      vertical_alignment: none
      parallax_text_color: default
    block:
      variations: center
  custom-5889:
    title: 'HTML personalizado'
    attributes:
      html: "<span class=\"fas fa-map-marker-alt\"></span> Avenida Santa Teresa de Jesús Miranda\n<br>\n<span class=\" fas fa-phone-alt\"></span> +58 (212) 263 17 44\n<br>\n<span class=\"fas fa-laptop\"></span> www.colegiosanignacio.com.ve\n<br>\n<span class=\" fas fa-calendar-alt\"></span> Lun - Vie: 7:30AM - 2:30PM"
    block:
      variations: nomarginall
  copyright-9780:
    title: 'Derechos de autor'
    attributes:
      enabled: 0
      owner: 'Meta Joomla 4 template by <a href="https://joomlead.com/" target="_blank">Joomlead</a>'
    block:
      variations: center
